### PR TITLE
virtualenv operation documentation added

### PR DESCRIPTION
**Pull request by mbad0la**
- Added steps to activate a virtual environment to work in.
- Updated .gitignore to ignore the virtualenv directory.

### CODE REVIEW

**Comment by kapilgarg1996** [comment]
Are you sure it will work ? Because project should be inside virtual environment directory, not the vice-versa

**Comment by mbad0la** [comment]
Can you refer me to a link where i might find relevant information about this? Because from what i've read, virtual environment directory is a child of the parent directory.

**Comment by kapilgarg1996** [comment]
Yes you are right. I red about it and there is not restriction on putting the virtualenv directory anywhere. We just need to activate the right one.So it looks good. Next time you do some adjustment then do it on a new branch as it will keep your master branch cleaned and synchronized.

**Comment by mbad0la** [comment]
@kapilgarg1996 i was actually hasty to push changes to my master, will keep that in mind the next time. Anyway, virtualenvs just have to be activated, though they can be placed anywhere.  
It is although a common practice to create a virtual env directory inside the project directory. Because, usually a setup script creates a virtualenv, activates it and installs all the dependencies.

**Pull request merged**
